#!/bin/bash
xgettext --language=Desktop --output=captain.pot data/*.desktop.in
xgettext --language=Python -cTRANSLATORS --keyword=_ --keyword=N_ --join-existing --output=captain.pot usr/lib/captain/*.py usr/bin/*
xgettext --language=Glade --join-existing --output=captain.pot usr/share/captain/*.ui
