#!/bin/bash
intltool-extract --type=gettext/glade usr/share/captain/captain.ui
xgettext --language=Desktop --output=captain.pot data/*.desktop.in
xgettext --language=Python -cTRANSLATORS --keyword=_ --keyword=N_ --join-existing --output=captain.pot usr/lib/captain/*.py usr/bin/* usr/share/captain/*.ui.h
rm -f usr/share/captain/*.ui.h
